#!/usr/bin/env node
/*
 * extract: read the mockup and write the two files nobody should type by hand.
 *
 *   node tools/extract.mjs           write src/theme/tokens.ts and src/strings/drawn.ts
 *   node tools/extract.mjs --check   fail if either is out of date
 *
 * WHY THIS IS A TOOL AND NOT A ONE-TIME COPY. Three people building from one
 * drawing will not agree on a colour by eye, and they will not phrase the same
 * sentence the same way. The mockup already holds both: 55 custom properties in
 * its stylesheet and every user-facing word it draws. Copying them by hand
 * makes a second source that drifts the first time the drawing changes.
 *
 * The mockup is generated upstream and regenerated when the design moves, so
 * this runs again and the difference shows up in a pull request.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const SRC = 'docs/design/mobile.html';
const OUT_TOKENS = 'src/theme/tokens.ts';
const OUT_STRINGS = 'src/strings/drawn.ts';
const CHECK = process.argv.includes('--check');

const html = readFileSync(SRC, 'utf8');
const results = [];
const add = (id, rule, ok, detail) => results.push({ id, rule, ok, detail });

/* ------------------------------------------------------------- tokens --- */

function block(re, what) {
  const m = html.match(re);
  if (!m) return null;
  const out = new Map();
  /* a value can hold a url() with its own semicolons and braces */
  for (const decl of m[1].split(/;(?![^(]*\))/)) {
    const i = decl.indexOf(':');
    if (i < 0) continue;
    const k = decl.slice(0, i).trim();
    if (!k.startsWith('--')) continue;
    out.set(k.slice(2), decl.slice(i + 1).trim());
  }
  if (!out.size) throw new Error('no custom properties in ' + what);
  return out;
}

const light = block(/:root\s*\{([^]*?)\}/, 'the light palette');
const dark = block(/prefers-color-scheme:\s*dark[^{]*\{\s*:root\s*\{([^]*?)\}/, 'the dark palette')
  || block(/\[data-theme="dark"\]\s*\{([^]*?)\}/, 'the dark palette');

const camel = k => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const lit = v => JSON.stringify(v);

function tokensFile() {
  const l = [...light].map(([k, v]) => '  ' + camel(k) + ': ' + lit(v) + ',').join('\n');
  const d = dark ? [...dark].map(([k, v]) => '  ' + camel(k) + ': ' + lit(v) + ',').join('\n') : '';
  return [
    '/* GENERATED by tools/extract.mjs from ' + SRC + '. Do not edit.',
    '   Run `node tools/extract.mjs` after the mockup changes. */',
    '',
    'export const light = {',
    l,
    '} as const;',
    '',
    /* NO DARK EXPORT WHEN THE DRAWING HAS NO DARK PALETTE, ADR 0008. `dark =
       light` would let code written for dark mode build and quietly draw
       light; a missing export makes the compiler find every such place. */
    ...(dark ? ['export const dark = {\n' + d + '\n} as const;\n'] : []),
    'export type TokenName = keyof typeof light;',
    '',
  ].join('\n');
}

/* ------------------------------------------------------------ strings --- */

const ENT = {
  '&nbsp;': ' ', '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"',
  '&rsquo;': '’', '&lsquo;': '‘', '&ldquo;': '“', '&rdquo;': '”',
  '&middot;': '·', '&deg;': '°', '&minus;': '−', '&hellip;': '…',
  '&times;': '×', '&bull;': '•', '&ccedil;': 'ç', '&eacute;': 'é',
  '&ndash;': '–', '&mdash;': '-', '&apos;': "'", '&shy;': '',
  '&thinsp;': ' ', '&ensp;': ' ', '&emsp;': ' ', '&frac12;': '½',
};
const decode = t => t.replace(/&[a-z]+;|&#[0-9]+;/g, m =>
  ENT[m] !== undefined ? ENT[m] : (m[1] === '#' ? String.fromCharCode(+m.slice(2, -1)) : m));

const BLOCK = new Set(['div', 'p', 'button', 'li', 'label', 'h1', 'h2', 'h3', 'h4',
  'section', 'header', 'footer', 'figure', 'figcaption', 'nav', 'ul', 'ol', 'td', 'th', 'tr', 'table']);

/* AN ELEMENT WITH WORDS OF ITS OWN IS A SENTENCE; ONE MADE ONLY OF ELEMENTS IS
   A ROW. The first version joined across every inline edge. That kept "the
   <b>navy overcoat</b>, good to" whole, which is right, and it also glued a
   weather row of three value-and-label pairs, an hour axis, a sort menu and a
   key beside its value into single strings no screen could use.

   The markup draws the line itself. Text written directly inside an element is
   read as one sentence: its inline edges leave a mark that becomes a space, or
   nothing before punctuation. An element whose only content is other elements,
   with nothing but whitespace between them, is a list of separate things, and
   each child is read on its own, recursively. A sentence therefore comes out
   exactly as it did before; only a run with no words of its own can split.

   Blocks are still hard boundaries, read as they always were, so the tree below
   is built one run at a time and never has to be well-formed across them. */
/* A PRIVATE-USE CODE POINT, because NUL inside a RegExp built from a string is
   not matched reliably and the text can never contain this one. */
const JOIN = String.fromCharCode(0xE000);
const VOID = new Set(['br', 'img', 'input', 'hr', 'wbr', 'source', 'area', 'col',
  'embed', 'meta', 'link', 'param', 'track']);
function readable(fragment) {
  const src = fragment.replace(/<svg[^]*?<\/svg>/g, '').replace(/<!--[^]*?-->/g, '');
  const out = [];
  /* a run's inline content as a small tree: {text}, {mark}, or {name, kids} */
  let run = { kids: [] };
  let open = [run];
  const top = () => open[open.length - 1];
  const tidy = t => decode(t)
    /* the class is written without ] or ), because a RegExp built from a
       string turns "\]" into a bare ] and closes the class early. */
    .replace(new RegExp(JOIN + '+(?=[,.;:!?%°])', 'g'), '')
    .replace(new RegExp(JOIN + '+', 'g'), ' ')
    .replace(/\s+/g, ' ').trim();
  const flat = n => n.kids.map(k => k.text !== undefined ? k.text
    : k.mark ? JOIN : JOIN + flat(k) + JOIN).join('');
  const own = n => n.kids.some(k => k.text !== undefined && k.text.trim() !== '');
  const items = n => own(n) ? [flat(n)] : n.kids.flatMap(k => k.kids ? items(k) : []);
  const flush = () => {
    for (const t of items(run).map(tidy)) if (t) out.push(t);
    run = { kids: [] };
    open = [run];
  };
  const tag = /<(\/?)([a-z0-9]+)([^>]*)>/g;
  let last = 0, m;
  while ((m = tag.exec(src))) {
    const text = src.slice(last, m.index);
    if (text) top().kids.push({ text });
    last = tag.lastIndex;
    const [, close, name, attrs] = m;
    if (BLOCK.has(name)) { flush(); continue; }
    if (VOID.has(name) || /[/][ \t]*$/.test(attrs)) { top().kids.push({ mark: true }); continue; }
    if (!close) {
      const el = { name, kids: [] };
      top().kids.push(el);
      open.push(el);
      continue;
    }
    /* close to the matching open, tolerating an inline tag left unclosed; a
       close with no open in this run is an edge like any other */
    let i = open.length - 1;
    while (i > 0 && open[i].name !== name) i--;
    if (i > 0) open.length = i;
    else top().kids.push({ mark: true });
  }
  const tail = src.slice(last);
  if (tail) top().kids.push({ text: tail });
  flush();
  return out;
}

const plates = [...html.matchAll(
  /<figure class="plate">([^]*?)<figcaption class="plate-cap"><span class="fig">([^<]+)<\/span>([^]*?)<\/figcaption>/g)];

const CHROME = new Set(['9:41', 'Today', 'Closet', 'Outfits', 'You']);
const screens = [];
for (const [, body, fig, cap] of plates) {
  const caption = decode(cap.replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ').trim().replace(/^·\s*/, '');
  const lines = readable(body).filter(t => !CHROME.has(t) && !/^[+−-]?[0-9]+°?$/.test(t));
  screens.push({ fig: fig.trim(), caption, lines: [...new Set(lines)] });
}

const slug = t => {
  const s = t.toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').trim().split(/\s+/).slice(0, 5);
  const k = s[0] + s.slice(1).map(w => w[0].toUpperCase() + w.slice(1)).join('');
  return /^[a-z]/.test(k) ? k : 's' + k;
};

function stringsFile() {
  const parts = [
    '/* GENERATED by tools/extract.mjs from ' + SRC + '. Do not edit.',
    '',
    '   Every user-facing sentence the mockup draws, grouped by the plate that',
    '   draws it. This is the inventory, not the final table: rename a key when a',
    '   screen uses it, and move it into src/strings/ proper. What it guarantees',
    '   is that nobody retypes a sentence from memory. */',
    '',
    'export const drawn = {',
  ];
  for (const s of screens) {
    parts.push('  /* Fig ' + s.fig.replace(/^Fig /, '') + ' ' + s.caption + ' */');
    parts.push('  ' + JSON.stringify('fig' + s.fig.replace(/^Fig /, '').toUpperCase()) + ': {');
    const seen = new Set();
    for (const t of s.lines) {
      let k = slug(t);
      while (seen.has(k)) k += '2';
      seen.add(k);
      parts.push('    ' + k + ': ' + lit(t) + ',');
    }
    parts.push('  },');
  }
  parts.push('} as const;', '');
  return parts.join('\n');
}

/* -------------------------------------------------------------- build --- */
/* THE CHECKS GATE THE WRITE, OR THEY ARE A REPORT. This used to write both
   files and then check them, so a run whose checks failed had already replaced
   the build inputs. Both files are now built in memory, every check below reads
   that, and nothing touches the disk until all of them pass. */
const want = { [OUT_TOKENS]: tokensFile(), [OUT_STRINGS]: stringsFile() };
const stalePaths = Object.keys(want)
  .filter(p => (existsSync(p) ? readFileSync(p, 'utf8') : null) !== want[p]);
const stale = stalePaths.length;

/* A GENERATOR CHECKS WHAT IT BUILT, not only that it ran. */
add('tokens-complete', 'every custom property in the mockup is in tokens.ts',
  [...light.keys()].every(k => want[OUT_TOKENS].includes(camel(k) + ':')),
  light.size + ' light tokens' + (dark ? ', ' + dark.size + ' dark' : ', no dark palette found'));
add('dark-covered', 'the dark palette overrides only names the light one declares',
  !dark || [...dark.keys()].every(k => light.has(k)),
  dark ? [...dark.keys()].filter(k => !light.has(k)).join(', ') || 'every dark name exists in light' : 'no dark block');
add('every-plate-read', 'every plate in the mockup contributes a strings group',
  screens.length === plates.length && screens.every(s => s.lines.length > 0),
  screens.length + ' plates, ' + screens.reduce((n, s) => n + s.lines.length, 0) + ' sentences');
{
  const leaked = screens.flatMap(s => s.lines.filter(t => /[<>]|&[a-z]+;|&#/.test(t))
    .map(t => s.fig + ' ' + t.slice(0, 40)));
  add('no-markup-leaked', 'no extracted string contains a tag or an entity',
    leaked.length === 0,
    leaked.length ? leaked.length + ' leaked, e.g. ' + leaked.slice(0, 3).join(' | ')
      : 'nothing drawn carries markup');
}
add('keys-unique', 'no group has two of the same key',
  (() => { for (const s of screens) { const k = new Set(); for (const t of s.lines) { const x = slug(t); if (k.has(x)) return false; k.add(x); } } return true; })(),
  'within a group, after the de-duplicating suffix');
/* -------------------------------------------------------------- write --- */
const refused = results.some(r => !r.ok);
let written = 0;
if (!CHECK && !refused) {
  for (const p of stalePaths) {
    mkdirSync(dirname(resolve(p)), { recursive: true });
    writeFileSync(p, want[p]);
    written++;
  }
}
add('up-to-date', CHECK ? 'both generated files match the mockup' : 'both generated files written',
  CHECK ? stale === 0 : true,
  CHECK ? (stale ? stale + ' file(s) are out of date, run node tools/extract.mjs' : 'both current')
    : refused ? 'nothing written: a check above failed, so both files are as they were'
    : (written ? written + ' file(s) rewritten' : 'both already current'));

let bad = 0;
for (const r of results) {
  if (!r.ok) bad++;
  console.log((r.ok ? 'ok   ' : 'FAIL ') + r.id.padEnd(18) + r.rule + (r.detail ? ': ' + r.detail : ''));
}
console.log(bad ? '\n' + bad + ' FAILING CHECKS' + (CHECK ? '' : ', nothing was written') + '\n' : '\nall checks pass\n');
process.exit(bad ? 1 : 0);
