#!/usr/bin/env node
/*
 * extract: read the mockup and write the two files nobody should type by hand.
 *
 *   node tools/extract.mjs           write src/theme/tokens.ts and src/strings/drawn.ts
 *   node tools/extract.mjs --check   fail if either is out of date
 *
 * WHY THIS IS A TOOL AND NOT A ONE-TIME COPY. Three people building from one
 * drawing will not agree on a colour by eye, and they will not phrase the same
 * sentence the same way. The mockup already holds both: 55 custom properties in
 * its stylesheet and every user-facing word it draws. Copying them by hand
 * makes a second source that drifts the first time the drawing changes.
 *
 * The mockup is generated upstream and regenerated when the design moves, so
 * this runs again and the difference shows up in a pull request.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const SRC = 'docs/design/mobile.html';
const OUT_TOKENS = 'src/theme/tokens.ts';
const OUT_STRINGS = 'src/strings/drawn.ts';
const CHECK = process.argv.includes('--check');

const html = readFileSync(SRC, 'utf8');
const results = [];
const add = (id, rule, ok, detail) => results.push({ id, rule, ok, detail });

/* ------------------------------------------------------------- tokens --- */

function block(re, what) {
  const m = html.match(re);
  if (!m) return null;
  const out = new Map();
  /* a value can hold a url() with its own semicolons and braces */
  for (const decl of m[1].split(/;(?![^(]*\))/)) {
    const i = decl.indexOf(':');
    if (i < 0) continue;
    const k = decl.slice(0, i).trim();
    if (!k.startsWith('--')) continue;
    out.set(k.slice(2), decl.slice(i + 1).trim());
  }
  if (!out.size) throw new Error('no custom properties in ' + what);
  return out;
}

const light = block(/:root\s*\{([^]*?)\}/, 'the light palette');
const dark = block(/prefers-color-scheme:\s*dark[^{]*\{\s*:root\s*\{([^]*?)\}/, 'the dark palette')
  || block(/\[data-theme="dark"\]\s*\{([^]*?)\}/, 'the dark palette');

const camel = k => k.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const lit = v => JSON.stringify(v);

function tokensFile() {
  const l = [...light].map(([k, v]) => '  ' + camel(k) + ': ' + lit(v) + ',').join('\n');
  const d = dark ? [...dark].map(([k, v]) => '  ' + camel(k) + ': ' + lit(v) + ',').join('\n') : '';
  return [
    '/* GENERATED by tools/extract.mjs from ' + SRC + '. Do not edit.',
    '   Run `node tools/extract.mjs` after the mockup changes. */',
    '',
    'export const light = {',
    l,
    '} as const;',
    '',
    dark ? 'export const dark = {\n' + d + '\n} as const;\n' : 'export const dark = light;\n',
    'export type TokenName = keyof typeof light;',
    '',
  ].join('\n');
}

/* ------------------------------------------------------------ strings --- */

const ENT = {
  '&nbsp;': ' ', '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"',
  '&rsquo;': '’', '&lsquo;': '‘', '&ldquo;': '“', '&rdquo;': '”',
  '&middot;': '·', '&deg;': '°', '&minus;': '−', '&hellip;': '…',
  '&times;': '×', '&bull;': '•', '&ccedil;': 'ç', '&eacute;': 'é',
  '&ndash;': '–', '&mdash;': '-', '&apos;': "'", '&shy;': '',
  '&thinsp;': ' ', '&ensp;': ' ', '&emsp;': ' ', '&frac12;': '½',
};
const decode = t => t.replace(/&[a-z]+;|&#[0-9]+;/g, m =>
  ENT[m] !== undefined ? ENT[m] : (m[1] === '#' ? String.fromCharCode(+m.slice(2, -1)) : m));

const BLOCK = new Set(['div', 'p', 'button', 'li', 'label', 'h1', 'h2', 'h3', 'h4',
  'section', 'header', 'footer', 'figure', 'figcaption', 'nav', 'ul', 'ol', 'td', 'th', 'tr', 'table']);

/* text of each element that holds no block-level child, which is the unit a
   person reads as one sentence. Inline spans inside it are joined. */
/* A PRIVATE-USE CODE POINT, because NUL inside a RegExp built from a string is
   not matched reliably and the text can never contain this one. */
const JOIN = String.fromCharCode(0xE000);
function readable(fragment) {
  const src = fragment.replace(/<svg[^]*?<\/svg>/g, '').replace(/<!--[^]*?-->/g, '');
  const out = [];
  const stack = [];
  let buf = '';
  const tag = /<(\/?)([a-z0-9]+)([^>]*)>/g;
  let last = 0, m;
  const flush = () => {
    const t = decode(buf)
      /* the class is written without ] or ), because a RegExp built from a
         string turns "\]" into a bare ] and closes the class early. */
      .replace(new RegExp(JOIN + '+(?=[,.;:!?%\u00b0])', 'g'), '')
      .replace(new RegExp(JOIN + '+', 'g'), ' ')
      .replace(/\s+/g, ' ').trim();
    if (t) out.push(t);
    buf = '';
  };
  while ((m = tag.exec(src))) {
    buf += src.slice(last, m.index);
    last = tag.lastIndex;
    const [, close, name] = m;
    /* AN INLINE TAG IS NOT A BOUNDARY, BUT IT IS A JOIN. The stat row draws a
       value and its label in two spans with no whitespace between them, and a
       sentence carries its emphasis the same way. Splitting on spans breaks the
       sentence; ignoring them glues "made for." to "Take a beanie". So an
       inline edge leaves a mark, and the mark becomes a space unless what
       follows is punctuation, where it becomes nothing. */
    if (!BLOCK.has(name)) { buf += JOIN; continue; }
    if (!close) { flush(); stack.push(name); } else { flush(); stack.pop(); }
  }
  buf += src.slice(last);
  flush();
  return out;
}

const plates = [...html.matchAll(
  /<figure class="plate">([^]*?)<figcaption class="plate-cap"><span class="fig">([^<]+)<\/span>([^]*?)<\/figcaption>/g)];

const CHROME = new Set(['9:41', 'Today', 'Closet', 'Outfits', 'You']);
const screens = [];
for (const [, body, fig, cap] of plates) {
  const caption = decode(cap.replace(/<[^>]+>/g, ' ')).replace(/\s+/g, ' ').trim().replace(/^·\s*/, '');
  const lines = readable(body).filter(t => !CHROME.has(t) && !/^[−-]?[0-9]+°?$/.test(t));
  screens.push({ fig: fig.trim(), caption, lines: [...new Set(lines)] });
}

const slug = t => {
  const s = t.toLowerCase().replace(/[^a-z0-9 ]+/g, ' ').trim().split(/\s+/).slice(0, 5);
  const k = s[0] + s.slice(1).map(w => w[0].toUpperCase() + w.slice(1)).join('');
  return /^[a-z]/.test(k) ? k : 's' + k;
};

function stringsFile() {
  const parts = [
    '/* GENERATED by tools/extract.mjs from ' + SRC + '. Do not edit.',
    '',
    '   Every user-facing sentence the mockup draws, grouped by the plate that',
    '   draws it. This is the inventory, not the final table: rename a key when a',
    '   screen uses it, and move it into src/strings/ proper. What it guarantees',
    '   is that nobody retypes a sentence from memory. */',
    '',
    'export const drawn = {',
  ];
  for (const s of screens) {
    parts.push('  /* Fig ' + s.fig.replace(/^Fig /, '') + ' ' + s.caption + ' */');
    parts.push('  ' + JSON.stringify('fig' + s.fig.replace(/^Fig /, '').toUpperCase()) + ': {');
    const seen = new Set();
    for (const t of s.lines) {
      let k = slug(t);
      while (seen.has(k)) k += '2';
      seen.add(k);
      parts.push('    ' + k + ': ' + lit(t) + ',');
    }
    parts.push('  },');
  }
  parts.push('} as const;', '');
  return parts.join('\n');
}

/* -------------------------------------------------------------- write --- */

const want = { [OUT_TOKENS]: tokensFile(), [OUT_STRINGS]: stringsFile() };
let stale = 0;
for (const [p, text] of Object.entries(want)) {
  const have = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (have === text) continue;
  stale++;
  if (!CHECK) {
    mkdirSync(dirname(resolve(p)), { recursive: true });
    writeFileSync(p, text);
  }
}

/* A GENERATOR CHECKS WHAT IT BUILT, not only that it ran. */
add('tokens-complete', 'every custom property in the mockup is in tokens.ts',
  [...light.keys()].every(k => want[OUT_TOKENS].includes(camel(k) + ':')),
  light.size + ' light tokens' + (dark ? ', ' + dark.size + ' dark' : ', no dark palette found'));
add('dark-covered', 'the dark palette overrides only names the light one declares',
  !dark || [...dark.keys()].every(k => light.has(k)),
  dark ? [...dark.keys()].filter(k => !light.has(k)).join(', ') || 'every dark name exists in light' : 'no dark block');
add('every-plate-read', 'every plate in the mockup contributes a strings group',
  screens.length === plates.length && screens.every(s => s.lines.length > 0),
  screens.length + ' plates, ' + screens.reduce((n, s) => n + s.lines.length, 0) + ' sentences');
{
  const leaked = screens.flatMap(s => s.lines.filter(t => /[<>]|&[a-z]+;|&#/.test(t))
    .map(t => s.fig + ' ' + t.slice(0, 40)));
  add('no-markup-leaked', 'no extracted string contains a tag or an entity',
    leaked.length === 0,
    leaked.length ? leaked.length + ' leaked, e.g. ' + leaked.slice(0, 3).join(' | ')
      : 'nothing drawn carries markup');
}
add('keys-unique', 'no group has two of the same key',
  (() => { for (const s of screens) { const k = new Set(); for (const t of s.lines) { const x = slug(t); if (k.has(x)) return false; k.add(x); } } return true; })(),
  'within a group, after the de-duplicating suffix');
add('up-to-date', CHECK ? 'both generated files match the mockup' : 'both generated files written',
  CHECK ? stale === 0 : true,
  CHECK ? (stale ? stale + ' file(s) are out of date, run node tools/extract.mjs' : 'both current')
    : (stale ? stale + ' file(s) rewritten' : 'both already current'));

let bad = 0;
for (const r of results) {
  if (!r.ok) bad++;
  console.log((r.ok ? 'ok   ' : 'FAIL ') + r.id.padEnd(18) + r.rule + (r.detail ? ': ' + r.detail : ''));
}
console.log(bad ? '\n' + bad + ' FAILING CHECKS\n' : '\nall checks pass\n');
process.exit(bad ? 1 : 0);
